### ISSUE TITLE
🐛 Unexpected Behavior in repository cloning & unexpected behavior in confirmation function

### ISSUE THREAD

**Issue by AlphaTechnolog** [xXDeathAbyssXx/gitd#1]
## 📝 Description

Well, this bug report consists in basically, two bug reports but in one lol.

The first thing i noticed was that, when the repo already exists, it asks for confirmation, but as Y is the capital letter, enter shouldn't mean **yes**?, well, yeah, that's the thing, when pressing enter, it canceled the operation.

And the second thing, was in the repository cloning, specifically, related with the branching. The usage of `gitd` says that you can put the git url and next, the branch, well, if you do something like:

```sh
gitd https://github.com/alphatechnolog/dotfiles bspwm
```

The output says that the downloaded branch is `welcome` (my master branch), but at the end, it pulled the desired branch, so it works great, but, shows incorrect information.

## 🔄 Steps to Reproduce

1. execute twice

```sh
gitd https://github.com/xXDeathAbyssXx/gitd.git
```
and when the confirmation pops up, you'll try to press enter to continue by removing the folder & recloning the repo, but instead, it just cancels the operation ;-;

2. for the branch thing, execute:

```sh
gitd https://github.com/alphatechnolog/dotfiles bspwm
```

and you'll see how it says welcome when it anyways pulled the bspwm branch

## 🤔 Expected Behavior

- Confirmation on enter should continue by recloning the repo and removing the existent one as desired
- Correct branch appears in the resume of the repo cloning process.

## 🚫 Actual Behavior

- Confirmation cancels the operation even if the default operation is **yes** (or should be)
- Main branch appears **always** in the repo cloning resume.

## 📸 Screenshots

![image](https://github.com/xXDeathAbyssXx/gitd/assets/54639968/6944c696-82d7-4226-9f7a-e4999fd3b5ae)
![image](https://github.com/xXDeathAbyssXx/gitd/assets/54639968/d4a9bd2d-eb7e-4606-8d65-a01cb301bf30)

## 🖥️ Environment Details

- Operating System: Gentoo Linux
- Zsh Version: `zsh 5.9 (x86_64-pc-linux-gnu)`
- gitd Version: dev

## 🛠️ Additional Context

N/A

## 💡 Possible Fix

N/A

## ✅ Checklist

- [x] I have checked the existing issues to ensure this bug has not been reported before.
- [x] I have included all the necessary information.
- [x] I have tested the bug on the latest version of gitd.

**Comment by xXDeathAbyssXx** [comment]
Thanks @AlphaTechnolog!

Done (https://github.com/xXDeathAbyssXx/gitd/commit/1b9b9a5b16f02604b88b7a7bc3f25025b144a099) and released.
